### ISSUE TITLE
Local take down sharelink and group revision

### ISSUE THREAD

**Issue by HaoPengNXDrive** [NXdriveBeta/WindowsApp#7]
Should take down these two numbers and put them together with tree revision. 

When calling Sync method, these two revisions are optional. Suggest passing these two so that local has knowledge that server sharelink/group revision has changed.

**Comment by NXdriveBeta** [comment]
Need some support on Connector project, there is a GetShareLinkChangeSet() method in Runtime. We just need to create a new REST method to call it and then add it to sdk.

**Comment by NXdriveBeta** [comment]
SDK is updated, but the file's hash returned is wrong, working on it.

**Comment by NXdriveBeta** [comment]
updated sdk and connector, hash is correct now. Still cannot get group changes, but not intended to fix it right now.
