### ISSUE TITLE
Login success page needs improvement.

### ISSUE THREAD

**Issue by HaoPengNXDrive** [NXdriveBeta/WindowsApp#9]
There is a static html file under:

WindowsApp\WebLogin\LoginOk.html

This page needs improvement.

**Comment by NXdriveBeta** [comment]
Is using the latest design.

The "." at the last line didn't show correctly on my computer (showing "?"). It is correct when you open the html directly tho.

**Comment by NXdriveBeta** [comment]
That dot symbol will fail to convert from string to byte and will be decoded as question mark. So I removed all dots.

**Comment by NXdriveBeta** [comment]
Should be fixed in 1.7.0.4
